### ISSUE TITLE
HELP！

### ISSUE THREAD

**Issue by Turing-zwl** [Lans1ng/OSSOD#1]
Thank you for your excellent work. How do I perform multi-GPU training?

**Comment by Lans1ng** [comment]
You can try the following script ( **nproc_per_node** represents the number of GPUs).
python -m torch.distributed.launch --nproc_per_node=2 --master_port=19005 train.py  --config configs/unbiased_teacher/split1/unbiased_teacher_ossod_id_mix_ood.py --launcher pytorch 

Please also note to modify the **gpu**  in the config.

**Comment by Turing-zwl** [comment]
Thanks!

**Comment by 1pengliu** [comment]
> 您可以尝试以下脚本 （ **nproc_per_node** 表示 GPU 的数量）。 python -m torch.distributed.launch --nproc_per_node=2 --master_port=19005 train.py --config configs/unbiased_teacher/split1/unbiased_teacher_ossod_id_mix_ood.py --launcher pytorch
> 
> 另请注意在配置中修改 **gpu**。

Windows系统能跑吗？

**Comment by Lans1ng** [comment]
> > 您可以尝试以下脚本 （ **nproc_per_node** 表示 GPU 的数量）。 python -m torch.distributed.launch --nproc_per_node=2 --master_port=19005 train.py --config configs/unbiased_teacher/split1/unbiased_teacher_ossod_id_mix_ood.py --launcher pytorch
> > 另请注意在配置中修改 **gpu**。
> 
> Windows系统能跑吗？

可以試試，應該可以。
